#Loading necessary packages
library(nlme)
library(tidyr)
library(dplyr)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(ggplot2)

#Loading datasets, datasets have been split up for easier loading
setwd('C:/Working directory')
data1<-read.csv('Week 1.csv', na='-', sep=';')
data2<-read.csv('Week 2.csv', na='-', sep=';')
data3<-read.csv('Week 3.csv', na='-', sep=';')
data4<-read.csv('Week 4.csv', na='-', sep=';')
data5<-read.csv('Week 5.csv', na='-', sep=';')
data6<-read.csv('Week 6.csv', na='-', sep=';')
data7<-read.csv('Week 7.csv', na='-', sep=';')
data8<-read.csv('Week 8.csv', na='-', sep=';')

####Creating LMMs per Week of Thaw####

#WOT1
nlme1.1<-lme(ALT~MossC, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.2<-lme(ALT~VascC, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.3<-lme(ALT~LichenC, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.4<-lme(ALT~RockC, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.8<-lme(ALT~cMm, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.11<-lme(ALT~Albedo, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.12<-lme(ALT~Org_layer, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.13<-lme(ALT~TDD, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.14<-lme(ALT~SD_height, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.15<-lme(ALT~DoSM, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.16<-lme(ALT~Max_snow, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.17<-lme(ALT~Aspect, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.18<-lme(ALT~PlantC, random=~1|Grid, data=data1, na.action = na.omit)
nlme1.19<-lme(ALT~Slope, random=~1|Grid, data=data1, na.action = na.omit)
#presenting results in table:
tab_model(nlme1.1, nlme1.2,nlme1.3,nlme1.4,nlme1.5,nlme1.6,nlme1.7, nlme1.8, nlme1.9,nlme1.10,
          nlme1.11,nlme1.12,nlme1.13,nlme1.14, nlme1.15, nlme1.16,nlme1.17,nlme1.19)

#WOT2
nlme2.1<-lme(ALT~MossC, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.2<-lme(ALT~VascC, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.3<-lme(ALT~LichenC, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.4<-lme(ALT~RockC, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.8<-lme(ALT~cMm, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.11<-lme(ALT~Albedo, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.12<-lme(ALT~Org_layer, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.13<-lme(ALT~TDD, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.14<-lme(ALT~SD_height, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.15<-lme(ALT~DoSM, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.16<-lme(ALT~Max_snow, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.17<-lme(ALT~Aspect, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.18<-lme(ALT~PlantC, random=~1|Grid, data=data2, na.action = na.omit)
nlme2.19<-lme(ALT~Slope, random=~1|Grid, data=data2, na.action = na.omit)
#presenting results in table:
tab_model(nlme2.1, nlme2.2,nlme2.3,nlme2.4,nlme2.5,nlme2.6,nlme2.7, nlme2.8, nlme2.9,nlme2.10,
          nlme2.11,nlme2.12,nlme2.13,nlme2.14, nlme2.15, nlme2.16,nlme2.17,nlme2.19)

#WOT3
nlme3.1<-lme(ALT~MossC, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.2<-lme(ALT~VascC, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.3<-lme(ALT~LichenC, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.4<-lme(ALT~RockC, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.8<-lme(ALT~cMm, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.11<-lme(ALT~Albedo, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.12<-lme(ALT~Org_layer, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.13<-lme(ALT~TDD, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.14<-lme(ALT~SD_height, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.15<-lme(ALT~DoSM, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.16<-lme(ALT~Max_snow, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.17<-lme(ALT~Aspect, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.18<-lme(ALT~PlantC, random=~1|Grid, data=data3, na.action = na.omit)
nlme3.19<-lme(ALT~Slope, random=~1|Grid, data=data3, na.action = na.omit)
#presenting results in table:
tab_model(nlme3.1, nlme3.2,nlme3.3,nlme3.4,nlme3.5,nlme3.6,nlme3.7, nlme3.8, nlme3.9,nlme3.10,
          nlme3.11,nlme3.12,nlme3.13,nlme3.14, nlme3.15, nlme3.16,nlme3.17,nlme3.19)

#WOT4
nlme4.1<-lme(ALT~MossC, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.2<-lme(ALT~VascC, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.3<-lme(ALT~LichenC, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.4<-lme(ALT~RockC, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.8<-lme(ALT~cMm, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.11<-lme(ALT~Albedo, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.12<-lme(ALT~Org_layer, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.13<-lme(ALT~TDD, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.14<-lme(ALT~SD_height, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.15<-lme(ALT~DoSM, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.16<-lme(ALT~Max_snow, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.17<-lme(ALT~Aspect, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.18<-lme(ALT~PlantC, random=~1|Grid, data=data4, na.action = na.omit)
nlme4.19<-lme(ALT~Slope, random=~1|Grid, data=data4, na.action = na.omit)
#presenting results in table:
tab_model(nlme4.1, nlme4.2,nlme4.3,nlme4.4,nlme4.5,nlme4.6,nlme4.7, nlme4.8, nlme4.9,nlme4.10,
           nlme4.11,nlme4.12,nlme4.13,nlme4.14, nlme4.15, nlme4.16,nlme4.17,nlme4.19)

#WOT5
nlme5.1<-lme(ALT~MossC, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.2<-lme(ALT~VascC, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.3<-lme(ALT~LichenC, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.4<-lme(ALT~RockC, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.8<-lme(ALT~cMm, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.11<-lme(ALT~Albedo, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.12<-lme(ALT~Org_layer, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.13<-lme(ALT~TDD, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.14<-lme(ALT~SD_height, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.15<-lme(ALT~DoSM, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.16<-lme(ALT~Max_snow, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.17<-lme(ALT~Aspect, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.18<-lme(ALT~PlantC, random=~1|Grid, data=data5, na.action = na.omit)
nlme5.19<-lme(ALT~Slope, random=~1|Grid, data=data5, na.action = na.omit)
#presenting results in table:
tab_model(nlme5.1, nlme5.2,nlme5.3,nlme5.4,nlme5.5,nlme5.6,nlme5.7, nlme5.8, nlme5.9,nlme5.10,
          nlme5.11,nlme5.12,nlme5.13,nlme5.14, nlme5.15, nlme5.16,nlme5.17,nlme5.19)

#WOT6
nlme6.1<-lme(ALT~MossC, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.2<-lme(ALT~VascC, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.3<-lme(ALT~LichenC, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.4<-lme(ALT~RockC, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.8<-lme(ALT~cMm, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.11<-lme(ALT~Albedo, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.12<-lme(ALT~Org_layer, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.13<-lme(ALT~TDD, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.14<-lme(ALT~SD_height, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.15<-lme(ALT~DoSM, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.16<-lme(ALT~Max_snow, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.17<-lme(ALT~Aspect, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.18<-lme(ALT~PlantC, random=~1|Grid, data=data6, na.action = na.omit)
nlme6.19<-lme(ALT~Slope, random=~1|Grid, data=data6, na.action = na.omit)
#presenting results in table:
tab_model(nlme6.1, nlme6.2,nlme6.3,nlme6.4,nlme6.5,nlme6.6,nlme6.7, nlme6.8, nlme6.9,nlme6.10,
          nlme6.11,nlme6.12,nlme6.13,nlme6.14, nlme6.15, nlme6.16,nlme6.17,nlme6.19)

#WOT7
nlme7.1<-lme(ALT~MossC, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.2<-lme(ALT~VascC, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.3<-lme(ALT~LichenC, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.4<-lme(ALT~RockC, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.8<-lme(ALT~cMm, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.11<-lme(ALT~Albedo, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.12<-lme(ALT~Org_layer, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.13<-lme(ALT~TDD, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.14<-lme(ALT~SD_height, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.15<-lme(ALT~DoSM, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.16<-lme(ALT~Max_snow, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.17<-lme(ALT~Aspect, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.18<-lme(ALT~PlantC, random=~1|Grid, data=data7, na.action = na.omit)
nlme7.19<-lme(ALT~Slope, random=~1|Grid, data=data7, na.action = na.omit)
#presenting results in table:
tab_model(nlme7.1, nlme7.2,nlme7.3,nlme7.4,nlme7.5,nlme7.6,nlme7.7, nlme7.8, nlme7.9,nlme7.10,
          nlme7.11,nlme7.12,nlme7.13,nlme7.14, nlme7.15, nlme7.16,nlme7.17,nlme7.19)

#WOT8
nlme8.1<-lme(ALT~MossC, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.2<-lme(ALT~VascC, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.3<-lme(ALT~LichenC, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.4<-lme(ALT~RockC, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.5<-lme(ALT~Avg_Moss_height, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.6<-lme(ALT~Avg_Vasc_height, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.7<-lme(ALT~Avg_Gram_height, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.8<-lme(ALT~cMm, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.9<-lme(ALT~Relative_elevation, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.10<-lme(ALT~cTmeanair, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.11<-lme(ALT~Albedo, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.12<-lme(ALT~Org_layer, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.13<-lme(ALT~TDD, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.14<-lme(ALT~SD_height, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.15<-lme(ALT~DoSM, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.16<-lme(ALT~Max_snow, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.17<-lme(ALT~Aspect, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.18<-lme(ALT~PlantC, random=~1|Grid, data=data8, na.action = na.omit)
nlme8.19<-lme(ALT~Slope, random=~1|Grid, data=data8, na.action = na.omit)
#presenting results in table:
tab_model(nlme8.1, nlme8.2,nlme8.3,nlme8.4,nlme8.5,nlme8.6,nlme8.7, nlme8.8, nlme8.9,nlme8.10,
          nlme8.11,nlme8.12,nlme8.13,nlme8.14, nlme8.15, nlme8.16,nlme8.17,nlme8.19)
